const RESTAPI_SECRETID = "";
const RESTAPI_SECRETKEY = "";

const SDKAPPID = "";
const SECRETKEY = "";

const PUSH_DOMAIN = "";
const AUTHENTICATION_KEY = "";
const VOD_SUBAPPID = 0;

module.exports = {
    RESTAPI_SECRETID,
    RESTAPI_SECRETKEY,

    SDKAPPID,
    SECRETKEY,

    PUSH_DOMAIN,
    AUTHENTICATION_KEY,

    VOD_SUBAPPID,
}